### ISSUE TITLE
Add jar files in release

### ISSUE THREAD

**Issue by wicksome** [naver/cover-checker#21]
maven package를 하지 않고,
바로 release에서 다운받아 사용할 수 있도록 jar파일이 추가되면 좋을 것 같습니다.

**Comment by ksmail13** [comment]
안녕하세요 cover-checker에 관심가져주셔서 감사합니다.
의견 주신대로 미리 빌드된 jar 를 [release]{https://github.com/naver/cover-checker/releases/tag/1.4.0} 에 추가 했습니다.

혹시 사용하시다 이슈 있으시면 또 문의 주세요.
감사합니다.
